// <auto-generated />
using System;
using FlickrToOneDrive.Contracts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FlickrToOneDrive.Contracts.Migrations
{
    [DbContext(typeof(CloudCopyContext))]
    partial class CloudCopyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("FlickrToOneDrive.Contracts.File", b =>
                {
                    b.Property<int>("FileId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FileName");

                    b.Property<int>("SessionId");

                    b.Property<string>("SourceUrl");

                    b.Property<int>("UploadStatus");

                    b.Property<string>("UploadStatusData");

                    b.HasKey("FileId");

                    b.HasIndex("SessionId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("FlickrToOneDrive.Contracts.Session", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DestinationFolder");

                    b.Property<bool>("Finished");

                    b.Property<DateTime>("Started");

                    b.HasKey("SessionId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("FlickrToOneDrive.Contracts.File", b =>
                {
                    b.HasOne("FlickrToOneDrive.Contracts.Session", "Session")
                        .WithMany("Files")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
